# Generated by Django 5.0.1 on 2024-01-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
