# Generated by Django 5.0.1 on 2024-01-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_serviceprovider_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='phone',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter your phone number', max_length=20, null=True),
        ),
    ]
