# Generated by Django 5.0.1 on 2024-02-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_serviceprovider_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20),
        ),
    ]
