# Generated by Django 5.0.1 on 2024-02-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_customer_latitude_alter_customer_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='near_by_landmark',
            field=models.CharField(default='nothing', max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter your phone number', max_length=15, null=True),
        ),
    ]
