# Generated by Django 5.0.1 on 2024-03-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
