# Generated by Django 5.0.1 on 2024-03-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_vehicles_vehicle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='image1',
            field=models.ImageField(default='workshop/default.jpg', upload_to='workshop/image1'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='image2',
            field=models.ImageField(default='workshop/default.jpg', upload_to='workshop/image2'),
        ),
    ]
